#!/bin/bash

DOTFILES_DIR=$(git rev-parse --show-toplevel)

setup_symlink() {
    if [[ "$1" == *"/"* ]]; then
        DIR=$(echo "$1" | grep -o ".*\/")
        mkdir -p "$HOME/$DIR"
    fi
    ln -sfv "$DOTFILES_DIR/$1" "$HOME/$1"
}

setup_copy() {
    if [[ "$1" == *"/"* ]]; then
        DIR=$(echo "$1" | grep -o ".*\/")
        mkdir -p "$HOME/$DIR"
    fi
    cp -rf "$DOTFILES_DIR/$1" "$HOME/$1"
}

setup_dotfiles() {
    setup_symlink .zshrc
    setup_symlink .tmux.conf
    setup_symlink .config/alacritty/alacritty.yml
    setup_symlink .config/nvim
}

if [ "$1" = 'dotfiles' ]; then
    setup_dotfiles
fi
